version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/weather_monitoring
      SPRING_DATASOURCE_USERNAME: rohan
      SPRING_DATASOURCE_PASSWORD: rohan
    networks:
      - weather-net

  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: weather_monitoring
      MYSQL_USER: rohan
      MYSQL_PASSWORD: rohan
      MYSQL_ROOT_PASSWORD: 9423635767
    networks:
      - weather-net

networks:
  weather-net:
